export { SettingsPopup } from './SettingsPopup/SettingsPopup'
export { Thumbnail } from './Thumbnail/Thumbnail'
export { Nav } from './Nav/Nav'
export { LoginForm } from './LoginForm/LoginForm'
export { RegisterForm } from './RegisterForm/RegisterForm'
export { HomeDisplay } from './HomeDisplay/HomeDisplay'
export { MainProfile } from './MainProfile/MainProfile'
